### ISSUE TITLE
Segmentation fault in sediment.c

### ISSUE THREAD

**Issue by guiaug** [ofringer/suntans#5]
I have experienced a segmentation fault and could pinpoint the issue to sediment.c, line 224 (If I have not mistaken). My guess is that the integer "j" is not the one to be used in this "for" loop.

**Comment by zyaj** [comment]
Thanks for the notification. The bug is due to the wrong pointer for edge indicator. Now it has been fixed.

**Comment by guiaug** [comment]
Thanks a lot Yun !
